# Generated by Django 6.1 on 2026-08-24 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('subtitles', 'Субтитры'), ('dubbing', 'Дубляж')], max_length=20, verbose_name='Режим обработки')),
                ('target_languages', models.JSONField(default=list, verbose_name='Целевые языки')),
                ('voice_mode', models.CharField(blank=True, choices=[('clone', 'Клонирование голоса'), ('preset_auto', 'Автоподбор пресет-голоса')], max_length=20, null=True, verbose_name='Режим голоса')),
                ('hardsub', models.BooleanField(default=False, verbose_name='Вшить субтитры в видео')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('queued', 'В очереди'), ('processing', 'Обрабатывается'), ('completed', 'Завершена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='created', max_length=20, verbose_name='Статус')),
                ('current_step', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текущий этап')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс (%)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('result_files', models.JSONField(blank=True, null=True, verbose_name='Файлы результата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата запуска')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=50, verbose_name='Этап')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус этапа')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало этапа')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец этапа')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Дополнительно')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.job', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Лог задачи',
                'verbose_name_plural': 'Логи задач',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='videos/%Y/%m/%d/', verbose_name='Исходный файл')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('detected_language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Определённый язык')),
                ('detected_language_confidence', models.FloatField(blank=True, null=True, verbose_name='Уверенность определения языка')),
                ('status', models.CharField(choices=[('uploading', 'Загрузка'), ('language_detection', 'Определение языка'), ('awaiting_user_choice', 'Ожидание выбора режима'), ('processing', 'Обработка'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='uploading', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10, verbose_name='Язык транскрипции')),
                ('segments', models.JSONField(default=list, verbose_name='Сегменты')),
                ('speakers', models.JSONField(default=dict, verbose_name='Спикеры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='core.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Транскрипция',
                'verbose_name_plural': 'Транскрипции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.video', verbose_name='Видео'),
        ),
    ]
